name: Build docker Image and push to repo

on:
  workflow_run:
    workflows:
      - "lint_and_execute_unit_test"
    types:
      - completed
env:
  IMAGE_NAME: ghcr.io/ashwin0794/flexport-devx-takehome/ashwin-flask-app:latest
  GITHUB_USERNAME: ashwin0794

jobs:
   build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
           python-version: '3.9.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and test docker image
        run: |
          pwd
          docker --version
          docker build -t ashwin-flask-app:latest .
          docker run --rm ashwin-flask-app:latest pytest tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.CR_PAT }}

      - name: Test Docker image after push
        run: |
          docker login ghcr.io -u ${{ env.GITHUB_USERNAME }}  -p ${{ secrets.CR_PAT }}
          docker pull ${{ env.IMAGE_NAME }}
          docker run -d --rm ${{ env.IMAGE_NAME }} pytest tests
