name: Build docker Image and push to repo

on:
  workflow_run:
    workflows:
      - "lint_and_execute_unit_test"
    types:
      - completed
env:
  IMAGE_NAME: ghcr.io/Ashwin0794/ashwin-flask-app:latest

jobs:
   build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
           python-version: '3.9.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}

      - name: Test Docker image
        run: |
          docker run --rm ${IMAGE_NAME} pytest tests

      - name: Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.CR_PAT }}
