name: Build docker Image and push to repo

on:
  workflow_run:
    workflows:
      - "lint_and_execute_unit_test"
    types:
      - completed
env:
  IMAGE_NAME: ghcr.io/ashwin0794/flexport-devx-takehome/ashwin-flask-app:latest
  REGISTRY: ghcr.io

jobs:
   build-test-publish:
    runs-on: ubuntu-latest
    steps:

      # set up python
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
           python-version: '3.9.12'

      # install pytest
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install pytest==7.2.2
          sudo pip3 install requests==2.28.2

      # checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # build and test docker image locally and github servers have docker installed
      - name: Build and test docker image
        run: |
          pwd
          docker --version
          docker build -t ashwin-flask-app:latest .
          docker run --rm ashwin-flask-app:latest pytest tests/unit
          docker run --rm ashwin-flask-app:latest pytest tests/functional

          # Need to modify the yml here
          # If testing the docker image fails or not 100%, then fail the workflow and print the reason.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

            # - name: Extract metadata (tags, labels) for Docker
            #   id: meta
            #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
            #   with:
            #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
            #   with:
            #     context: .
            #     push: true
            #     tags: ${{ steps.meta.outputs.tags }},latest
            #     labels: ${{ steps.meta.outputs.labels }}

      # if docker push fails, then fail the workflow
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.CR_PAT }}
