name: "Testing rock_paper_scissors on k8s clusterlocally using Kind"

on:
  workflow_run:
    workflows:
      - "Build docker Image and push to repo"
    types:
      - completed

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghrc.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull image
        run: docker pull ghcr.io/ashwin0794/flexport-devx-takehome/ashwin-flask-app:latest
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          kubectl get nodes
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${{ env.KUBECONFIG }}
      - name: Deploy Application
        run: |
          docker pull ghcr.io/ashwin0794/flexport-devx-takehome/ashwin-flask-app:latest
          kubectl create deployment kubernetes-bootcamp --image=ghcr.io/ashwin0794/flexport-devx-takehome/ashwin-flask-app:latest
          kubectl get pods
          kubectl describe pod $(kubectl get pods | awk '/<pod-label-selector>/{print $1}')
          kubectl logs $(kubectl get pods | awk '/<pod-label-selector>/{print $1}')
          kubectl get deployments
          kubectl wait pods --for condition=Ready --all --timeout=5m
          kubectl expose deployment/kubernetes-bootcamp --type=NodePort --port 8080
