name: lint_and_execute_unit_test

on: [push]

jobs:

  format_check:
    steps:
      run: black --diff .

  lint_code:
    steps:
      run: find -name "*.py" -exec pylint {} +

  code_coverage:
    steps:
      run: PYTHONPATH="./src" coverage run -m pytest
