name: lint_and_execute_unit_test

on: [push]

jobs:

  install_dependecies:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          chmod +x install_dependencies.sh
          ./install_dependencies.sh

      - name: debug info
        run: |
          black --version
          pytest --version
          flask --version
          pylint --version
          coverage --version
          pwd
      - name: check formatting
        run: black --diff .
      - name: lint the code
        run: find ./  -name "*.py" -exec pylint {} +
      - name: code coverage
        run: PYTHONPATH="./src" coverage run -m pytest
