name: lint_and_execute_unit_test

on: [push]

jobs:

  lint_and_execute_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
           python-version: '3.9.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: debug info
        run: |
          black --version
          pytest --version
          flask --version
          pylint --version
          coverage --version
          pwd
      - name: check formatting
        run: |
          black --diff .
          black .
      - name: lint the code
        run: find ./  -name "*.py" -exec pylint {} +
        continue-on-error: true
      - name: code coverage
        run: |
          PYTHONPATH="./src" coverage run -m pytest
          PYTHONPATH="./src" coverage report -m | grep -e 'src' -e 'tests/'
