name: lint_and_execute_unit_test

on: [push]

jobs:

  install_dependecies:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install packages
        run:
          chmod +x install_dependencies.sh
          ./install_dependencies.sh

      - name: print all dependencies
        run:
          black --version
          pytest --version
          flask --verison
          pylint --verison
          coverage --version
